Repository avast/scala-server-toolkit, pull requests merged in 2019-11, with the labels that each got.

#65 Update scalafmt-core to 2.2.2
  .scalafmt.conf
Labels: dependency-update

#68 Update sbt-mdoc to 2.0.0
  project/plugins.sbt
Labels: dependency-update

#69 Update micrometer-core, ... to 1.3.1
  project/Dependencies.scala
Labels: dependency-update

#56 feat: Add monix-catnap module with PureConfig integration
  build.sbt
  docs/doobie.md
  docs/flyway.md
  docs/http4s.md
  docs/index.md
  docs/jvm.md
  docs/micrometer.md
  docs/monix-catnap.md
  docs/pureconfig.md
  docs/rationale.md
  docs/ssl-config.md
  example/mdoc/flyway.md
  example/mdoc/http4s.md
  example/mdoc/index.md
  example/mdoc/jvm.md
  example/mdoc/monix-catnap.md
  example/src/main/resources/reference.conf
  example/src/main/scala/com/avast/sst/example/Main.scala
  example/src/main/scala/com/avast/sst/example/config/Configuration.scala
  example/src/main/scala/com/avast/sst/example/module/Http4sRoutingModule.scala
  http4s-client-monix-catnap/src/main/scala/com/avast/sst/http4s/client/monix/catnap/Http4sClientCircuitBreakerModule.scala
  http4s-client-monix-catnap/src/main/scala/com/avast/sst/http4s/client/monix/catnap/HttpStatusClassifier.scala
  monix-catnap-micrometer/src/main/scala/com/avast/sst/monix/catnap/micrometer/MicrometerCircuitBreakerMetricsModule.scala
  monix-catnap-pureconfig/src/main/scala/com/avast/sst/monix/catnap/pureconfig/ConfigReaders.scala
  monix-catnap-pureconfig/src/main/scala/com/avast/sst/monix/catnap/pureconfig/implicits.scala
  monix-catnap/src/main/scala/com/avast/sst/monix/catnap/CircuitBreakerConfig.scala
  monix-catnap/src/main/scala/com/avast/sst/monix/catnap/CircuitBreakerMetrics.scala
  monix-catnap/src/main/scala/com/avast/sst/monix/catnap/CircuitBreakerModule.scala
  project/Dependencies.scala
Labels: feature

#70 Update http4s-blaze-client, ... to 0.20.13
  project/Dependencies.scala
Labels: dependency-update

#71 feat: Allow configuration of PureConfig naming conventions
  docs/pureconfig.md
  doobie-hikari-pureconfig/src/main/scala/com/avast/sst/doobie/pureconfig/implicits.scala
  example/mdoc/pureconfig.md
  flyway-pureconfig/src/main/scala/com/avast/sst/flyway/pureconfig/implicits.scala
  http4s-client-blaze-pureconfig/src/main/scala/com/avast/sst/http4s/client/pureconfig/implicits.scala
  http4s-server-blaze-pureconfig/src/main/scala/com/avast/sst/http4s/server/pureconfig/implicits.scala
  jvm-pureconfig/src/main/scala/com/avast/sst/jvm/pureconfig/implicits.scala
  micrometer-jmx-pureconfig/src/main/scala/com/avast/sst/micrometer/jmx/pureconfig/implicits.scala
  micrometer-statsd-pureconfig/src/main/scala/com/avast/sst/micrometer/statsd/pureconfig/implicits.scala
  monix-catnap-pureconfig/src/main/scala/com/avast/sst/monix/catnap/pureconfig/implicits.scala
Labels: feature

#72 Update monix-catnap, monix-eval to 3.1.0
  project/Dependencies.scala
Labels: dependency-update

#73 Update sbt-mdoc to 2.0.1
  project/plugins.sbt
Labels: dependency-update

#75 Update ssl-config-core to 0.4.1
  project/Dependencies.scala
Labels: dependency-update

#76 Update sbt-mdoc to 2.0.2
  project/plugins.sbt
Labels: dependency-update

#78 Update/zio 1.0.0 rc17
  docs/doobie.md
  docs/micrometer.md
  example/mdoc/doobie.md
  example/mdoc/micrometer.md
  example/src/main/scala/com/avast/sst/example/Main.scala
  project/Dependencies.scala
Labels: dependency-update

#79 Update sbt to 1.3.4
  project/build.properties
Labels: dependency-update

#80 Update zio-interop-cats to 2.0.0.0-RC9
  project/Dependencies.scala
Labels: dependency-update

#81 Update sbt-scalafix to 0.9.9
  project/plugins.sbt
Labels: dependency-update

#82 Update flyway-core to 6.1.0
  project/Dependencies.scala
Labels: dependency-update

#83 Update http4s-blaze-client, ... to 0.20.14
  project/Dependencies.scala
Labels: dependency-update

#84 Update sbt-tpolecat to 0.1.9
  project/plugins.sbt
Labels: dependency-update

#85 Update sbt-tpolecat to 0.1.10
  project/plugins.sbt
Labels: dependency-update

#74 Feat/datastax module
  build.sbt
  cassandra-datastax-driver-pureconfig/src/main/scala/com/avast/sst/datastax/pureconfig/ConfigReaders.scala
  cassandra-datastax-driver-pureconfig/src/main/scala/com/avast/sst/datastax/pureconfig/implicits.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/CassandraDatastaxDriverModule.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/DatastaxHelper.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/CassandraDatastaxDriverConfig.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/advanced.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/basic.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/package.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/profile.scala
  docs/cassandra-datastax-driver.md
  example/docker-compose.yml
  example/mdoc/cassandra-datastax-driver.md
  example/src/main/resources/reference.conf
  example/src/main/scala/com/avast/sst/example/Main.scala
  example/src/main/scala/com/avast/sst/example/config/Configuration.scala
  project/Dependencies.scala
Labels: documentation, feature

#86 Update java-driver-core to 4.3.0
  project/Dependencies.scala
Labels: dependency-update

#89 Update zio-interop-cats to 2.0.0.0-RC10
  project/Dependencies.scala
Labels: dependency-update

#90 Update http4s-blaze-client, ... to 0.20.15
  project/Dependencies.scala
Labels: dependency-update

#91 Update scalatest to 3.1.0
  http4s-client-blaze/src/test/scala/com/avast/sst/http4s/client/Http4SBlazeClientTest.scala
  http4s-server-blaze/src/test/scala/com/avast/sst/http4s/server/Http4sBlazeServerModuleTest.scala
  http4s-server-micrometer/src/test/scala/com/avast/sst/http4s/server/micrometer/HttpStatusMetricsTest.scala
  http4s-server-micrometer/src/test/scala/com/avast/sst/http4s/server/micrometer/MicrometerHttp4sMetricsOpsModuleTest.scala
  http4s-server-micrometer/src/test/scala/com/avast/sst/http4s/server/micrometer/RouteMetricsTest.scala
  http4s-server/src/test/scala/com/avast/sst/http4s/server/middleware/CorrelationIdMiddlewareTest.scala
  jvm/src/test/scala/com/avast/sst/jvm/execution/ExecutorModuleTest.scala
  jvm/src/test/scala/com/avast/sst/jvm/system/console/ConsoleModuleTest.scala
  jvm/src/test/scala/com/avast/sst/jvm/system/random/RandomModuleTest.scala
  project/Dependencies.scala
  pureconfig/src/test/scala/com/avast/sst/pureconfig/PureConfigModuleTest.scala
  ssl-config/src/test/scala/com/avast/sst/ssl/SslContextModuleTest.scala
Labels: dependency-update
