Repository avast/scala-server-toolkit, pull requests merged in 2019-10, with the labels that each got.

#36 build: Add .mergify.yml file for automatic PR merging
  .mergify.yml
Labels: feature

#37 Update sbt-mdoc to 1.3.6
  project/plugins.sbt
Labels: dependency-update

#42 build: Update ZIO
  bundle-zio-http4s-blaze/src/main/scala/com/avast/sst/bundle/ZioResourceApp.scala
  bundle-zio-http4s-blaze/src/main/scala/com/avast/sst/bundle/ZioServerApp.scala
  project/Dependencies.scala
Labels: dependency-update

#43 feat: micrometer-statsd
  build.sbt
  micrometer-jmx/src/main/scala/com/avast/sst/micrometer/jmx/MicrometerJmxConfig.scala
  micrometer-jmx/src/main/scala/com/avast/sst/micrometer/jmx/MicrometerJmxModule.scala
  micrometer-statsd-pureconfig/src/main/scala/com/avast/sst/micrometer/statsd/pureconfig/ConfigReaders.scala
  micrometer-statsd-pureconfig/src/main/scala/com/avast/sst/micrometer/statsd/pureconfig/implicits.scala
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDConfig.scala
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDModule.scala
  project/Dependencies.scala
Labels: feature

#45 Update scalafmt-core to 2.2.0
  .scalafmt.conf
Labels: dependency-update

#44 feat: Add ssl-config module
  build.sbt
  docs/index.md
  docs/jvm.md
  docs/micrometer.md
  docs/ssl-config.md
  example/mdoc/index.md
  example/mdoc/jvm.md
  example/mdoc/ssl-config.md
  http4s-client-blaze-pureconfig/src/main/scala/com/avast/sst/http4s/client/pureconfig/ConfigReaders.scala
  http4s-client-blaze/src/main/scala/com/avast/sst/http4s/client/Http4sBlazeClientConfig.scala
  http4s-client-blaze/src/main/scala/com/avast/sst/http4s/client/Http4sBlazeClientModule.scala
  jvm-pureconfig/src/main/scala/com/avast/sst/jvm/pureconfig/ConfigReaders.scala
  jvm/src/main/scala/com/avast/sst/jvm/ssl/KeyStoreConfig.scala
  jvm/src/main/scala/com/avast/sst/jvm/ssl/KeyStoreType.scala
  jvm/src/main/scala/com/avast/sst/jvm/ssl/Protocol.scala
  jvm/src/main/scala/com/avast/sst/jvm/ssl/SslContextConfig.scala
  jvm/src/main/scala/com/avast/sst/jvm/ssl/SslContextModule.scala
  jvm/src/test/scala/com/avast/sst/jvm/ssl/SslContextModuleTest.scala
  project/Dependencies.scala
  ssl-config/src/main/scala/com/avast/sst/ssl/Slf4jLogger.scala
  ssl-config/src/main/scala/com/avast/sst/ssl/SslContextModule.scala
  ssl-config/src/test/resources/application.conf
  ssl-config/src/test/resources/truststore.jks
  ssl-config/src/test/scala/com/avast/sst/ssl/SslContextModuleTest.scala
Labels: feature

#52 Update scalafmt-core to 2.2.1
  .scalafmt.conf
Labels: dependency-update

#46 Add doobie-hikari module
  build.sbt
  docs/doobie.md
  docs/index.md
  docs/jvm.md
  docs/micrometer.md
  doobie-hikari-pureconfig/src/main/scala/com/avast/sst/doobie/pureconfig/ConfigReaders.scala
  doobie-hikari-pureconfig/src/main/scala/com/avast/sst/doobie/pureconfig/implicits.scala
  doobie-hikari/src/main/scala/com/avast/sst/doobie/DoobieHikariConfig.scala
  doobie-hikari/src/main/scala/com/avast/sst/doobie/DoobieHikariModule.scala
  example/README.md
  example/docker-compose.yml
  example/mdoc/doobie.md
  example/mdoc/index.md
  example/mdoc/jvm.md
  example/mdoc/micrometer.md
  example/src/main/resources/reference.conf
  example/src/main/scala/com/avast/sst/example/Main.scala
  example/src/main/scala/com/avast/sst/example/config/Configuration.scala
  example/src/main/scala/com/avast/sst/example/module/Http4sRoutingModule.scala
  example/src/main/scala/com/avast/sst/example/service/RandomService.scala
  project/Dependencies.scala
Labels: feature

#53 Add Flyway support
  build.sbt
  docs/flyway.md
  docs/index.md
  example/mdoc/flyway.md
  example/mdoc/index.md
  flyway-pureconfig/src/main/scala/com/avast/sst/flyway/pureconfig/ConfigReaders.scala
  flyway-pureconfig/src/main/scala/com/avast/sst/flyway/pureconfig/implicits.scala
  flyway/src/main/scala/com/avast/sst/flyway/FlywayConfig.scala
  flyway/src/main/scala/com/avast/sst/flyway/FlywayModule.scala
  project/Dependencies.scala
Labels: feature

#54 Update sbt-missinglink to 0.2.0
  project/plugins.sbt
Labels: dependency-update

#55 Update sbt-scalafmt to 2.2.0
  project/plugins.sbt
Labels: dependency-update

#57 build: Downgrade doobie to 0.7.x because of compatibility with http4s…
  doobie-hikari/src/main/scala/com/avast/sst/doobie/DoobieHikariModule.scala
  project/Dependencies.scala
Labels: bug

#58 Update sbt-scalafmt to 2.2.1
  project/plugins.sbt
Labels: dependency-update

#60 Update zio to 1.0.0-RC16
  project/Dependencies.scala
Labels: dependency-update

#62 Update zio-interop-cats to 2.0.0.0-RC7
  project/Dependencies.scala
Labels: dependency-update

#63 Update http4s-blaze-client, ... to 0.20.12
  project/Dependencies.scala
Labels: dependency-update

#64 Update sbt-scalafix to 0.9.8
  project/plugins.sbt
Labels: dependency-update

#66 Update slf4j-api to 1.7.29
  project/Dependencies.scala
Labels: dependency-update
