Repository avast/scala-server-toolkit, pull requests merged in 2020-05, with the labels that each got.

#231 Update scalafmt-core to 2.5.1
  .scalafmt.conf
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/basic.scala
  example/src/main/scala/com/avast/sst/example/Main.scala
  example/src/main/scala/com/avast/sst/example/service/RandomService.scala
  grpc-server-micrometer/src/main/scala/com/avast/sst/grpc/server/micrometer/MonitoringServerInterceptor.scala
  http4s-server-blaze/src/main/scala/com/avast/sst/http4s/server/Http4sBlazeServerModule.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/RouteMetrics.scala
  http4s-server/src/main/scala/com/avast/sst/http4s/server/middleware/CorrelationIdMiddleware.scala
  jvm/src/main/scala/com/avast/sst/jvm/execution/ForkJoinPoolConfig.scala
  jvm/src/main/scala/com/avast/sst/jvm/system/console/Console.scala
  jvm/src/main/scala/com/avast/sst/jvm/system/random/Random.scala
  micrometer-jmx/src/main/scala/com/avast/sst/micrometer/jmx/TypeScopeNameObjectNameFactory.scala
  monix-catnap/src/main/scala/com/avast/sst/monix/catnap/CircuitBreakerMetrics.scala
  ssl-config/src/main/scala/com/avast/sst/ssl/Slf4jLogger.scala
  ssl-config/src/main/scala/com/avast/sst/ssl/SslContextModule.scala
Labels: dependency-update

#232 Update micrometer-core, ... to 1.5.1
  project/Dependencies.scala
Labels: dependency-update

#234 Update scalatest to 3.1.2
  project/Dependencies.scala
Labels: dependency-update

#233 Update scalafmt-core to 2.5.2
  .scalafmt.conf
Labels: dependency-update

#235 Update sbt-microsites to 1.2.1
  project/plugins.sbt
Labels: dependency-update

#237 Update java-driver-core to 4.6.1
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/CassandraDatastaxDriverModule.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/advanced.scala
  project/Dependencies.scala
Labels: dependency-update

#238 Update silencer-lib, silencer-plugin to 1.7.0
  project/Dependencies.scala
Labels: dependency-update

#239 Update flyway-core to 6.4.2
  project/Dependencies.scala
Labels: dependency-update

#240 Update sbt-scalafmt to 2.4.0
  project/plugins.sbt
Labels: dependency-update

#241 Update zio to 1.0.0-RC19
  project/Dependencies.scala
Labels: dependency-update

#242 Update zio-interop-cats to 2.0.0.0-RC14
  project/Dependencies.scala
Labels: dependency-update

#243 Update zio to 1.0.0-RC19-1
  project/Dependencies.scala
Labels: dependency-update

#245 Update zio to 1.0.0-RC19-2
  project/Dependencies.scala
Labels: dependency-update

#244 fix: Wrong use of Micrometer metrics
  build.sbt
  cats-effect/src/main/scala/com/avast/sst/catseffect/TimeUtils.scala
  cats-effect/src/main/scala/com/avast/sst/catseffect/syntax/TimeSyntax.scala
  cats-effect/src/main/scala/com/avast/sst/catseffect/syntax/package.scala
  cats-effect/src/test/scala/com/avast/sst/catseffect/syntax/FOpsTest.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/HttpStatusMetrics.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/MicrometerHttp4sMetricsOpsModule.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/MicrometerHttp4sServerMetricsModule.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/RouteMetrics.scala
  http4s-server-micrometer/src/test/scala/com/avast/sst/http4s/server/micrometer/HttpStatusMetricsTest.scala
  http4s-server-micrometer/src/test/scala/com/avast/sst/http4s/server/micrometer/MicrometerHttp4sMetricsOpsModuleTest.scala
  http4s-server-micrometer/src/test/scala/com/avast/sst/http4s/server/micrometer/RouteMetricsTest.scala
Labels: bug, feature

#246 feat: Implement Fs2KafkaModule
  build.sbt
  fs2-kafka-pureconfig/src/main/scala/com/avast/sst/fs2kafka/pureconfig/ConfigReaders.scala
  fs2-kafka-pureconfig/src/main/scala/com/avast/sst/fs2kafka/pureconfig/implicits.scala
  fs2-kafka/src/main/scala/com/avast/sst/fs2kafka/ConsumerConfig.scala
  fs2-kafka/src/main/scala/com/avast/sst/fs2kafka/Fs2KafkaModule.scala
  fs2-kafka/src/main/scala/com/avast/sst/fs2kafka/ProducerConfig.scala
  fs2-kafka/src/test/scala/com/avast/sst/fs2kafka/Fs2KafkaModuleTest.scala
  fs2-kafka/src/test/scala/com/avast/sst/fs2kafka/KafkaConfigTest.scala
  grpc-server/src/main/scala/com/avast/sst/grpc/server/GrpcServerModule.scala
  project/Dependencies.scala
  site/docs/subprojects/fs2-kafka.md
  site/menu.yml
Labels: feature

#247 feat: Allow to set custom underlying consumer/producer in fs2-kafka
  fs2-kafka/src/main/scala/com/avast/sst/fs2kafka/Fs2KafkaModule.scala
Labels: feature

#249 Update scalafmt-core to 2.5.3
  .scalafmt.conf
Labels: dependency-update

#248 Update zio to 1.0.0-RC20
  bundle-zio-http4s-blaze/src/main/scala/com/avast/sst/bundle/ZioResourceApp.scala
  bundle-zio-http4s-blaze/src/main/scala/com/avast/sst/bundle/ZioServerApp.scala
  project/Dependencies.scala
Labels: dependency-update

#250 Update flyway-core to 6.4.3
  project/Dependencies.scala
Labels: dependency-update

#251 Update sbt-scalafix to 0.9.16
  project/plugins.sbt
Labels: dependency-update

#252 Update sbt to 1.3.11
  project/build.properties
Labels: dependency-update

#253 Update sbt to 1.3.12
  project/build.properties
Labels: dependency-update
