Repository avast/scala-server-toolkit, pull requests merged in 2020-04, with the labels that each got.

#197 Update postgresql to 42.2.12
  project/Dependencies.scala
Labels: dependency-update

#198 Update sbt-missinglink to 0.3.1
  project/plugins.sbt
Labels: dependency-update

#200 Update http4s-blaze-client, ... to 0.21.3
  project/Dependencies.scala
Labels: dependency-update

#201 Update grpc-netty-shaded, grpc-protobuf, ... to 1.28.1
  project/Dependencies.scala
Labels: dependency-update

#202 Update doobie-core, doobie-hikari to 0.9.0
  project/Dependencies.scala
Labels: dependency-update

#203 Update flyway-core to 6.3.3
  project/Dependencies.scala
Labels: dependency-update

#205 Update sbt-scalafmt to 2.3.4
  project/plugins.sbt
Labels: dependency-update

#206 Update sbt-scalafix to 0.9.14
  project/plugins.sbt
Labels: dependency-update

#207 Update sbt to 1.3.10
  project/build.properties
Labels: dependency-update

#208 Update scala-collection-compat to 2.1.5
  project/Dependencies.scala
Labels: dependency-update

#209 Update cats-effect to 2.1.3
  project/Dependencies.scala
Labels: dependency-update

#210 feat: Add StatsD prefix configuration
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDConfig.scala
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDModule.scala
Labels: feature

#211 Update scala-collection-compat to 2.1.6
  project/Dependencies.scala
Labels: dependency-update

#212 Update sbt-scalafix to 0.9.15
  project/plugins.sbt
Labels: dependency-update

#213 Update sbt-microsites to 1.2.0
  project/plugins.sbt
Labels: dependency-update

#214 Update flyway-core to 6.4.0
  project/Dependencies.scala
Labels: dependency-update

#215 Update sbt-ci-release to 1.5.3
  project/plugins.sbt
Labels: dependency-update

#216 Update grpc-netty-shaded, grpc-protobuf, ... to 1.29.0
  project/Dependencies.scala
Labels: dependency-update

#218 fix: Use the new way of enabling SemanticDB to fix IDEA compile issue
  project/BuildSettings.scala
Labels: build

#219 feat: Add subproject micrometer with generic PrefixMeterFilter
  build.sbt
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDConfig.scala
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDModule.scala
  micrometer/src/main/scala/com/avast/sst/micrometer/PrefixMeterFilter.scala
  micrometer/src/test/scala/com/avast/sst/micrometer/PrefixMeterFilterTest.scala
Labels: bug, feature

#220 Update micrometer-core, ... to 1.4.2
  project/Dependencies.scala
Labels: dependency-update

#221 Update monix-catnap, monix-eval to 3.2.0
  project/Dependencies.scala
Labels: dependency-update

#222 Update java-driver-core to 4.6.0
  project/Dependencies.scala
Labels: dependency-update

#224 feat: Add support for Hikari DataSource properties
  doobie-hikari/src/main/scala/com/avast/sst/doobie/DoobieHikariConfig.scala
  doobie-hikari/src/main/scala/com/avast/sst/doobie/DoobieHikariModule.scala
Labels: feature

#225 Update micrometer-core, ... to 1.5.0
  project/Dependencies.scala
Labels: dependency-update

#226 Update/http4s server 0.21.4
  http4s-server-blaze/src/main/scala/com/avast/sst/http4s/server/Http4sBlazeServerModule.scala
  http4s-server/src/test/scala/com/avast/sst/http4s/server/middleware/CorrelationIdMiddlewareTest.scala
  project/Dependencies.scala
Labels: dependency-update

#227 Update zio-interop-cats to 2.0.0.0-RC13
  project/Dependencies.scala
Labels: dependency-update

#228 Update monix-catnap, monix-eval to 3.2.1
  project/Dependencies.scala
Labels: dependency-update

#229 Update flyway-core to 6.4.1
  project/Dependencies.scala
Labels: dependency-update
