Repository avast/scala-server-toolkit, pull requests merged in 2020-02, with the labels that each got.

#138 Update sbt to 1.3.8
  project/build.properties
Labels: dependency-update

#139 Update flyway-core to 6.2.2
  project/Dependencies.scala
Labels: dependency-update

#140 Update postgresql to 42.2.10
  project/Dependencies.scala
Labels: dependency-update

#142 build: Setup release-drafter
  .github/release-drafter.yml
  .github/workflows/build.yml
Labels: build

#144 Update sbt-ci-release to 1.5.2
  project/plugins.sbt
Labels: dependency-update

#143 Update cats-effect to 2.1.1
  project/Dependencies.scala
Labels: dependency-update

#145 Update http4s-blaze-client, ... to 0.21.0
  project/Dependencies.scala
Labels: dependency-update

#146 build: Set the default Scala version to 2.13.1
  .scala-steward.conf
  .scalafix.conf
  build.sbt
  doobie-hikari/src/main/scala/com/avast/sst/doobie/DoobieHikariModule.scala
  project/BuildSettings.scala
  project/Dependencies.scala
Labels: build, dependency-update

#147 fix: Remove WartRemover as it was not working properly on Scala 2.13
  .scalafix.conf
  README.md
  build.sbt
  flyway/src/main/scala/com/avast/sst/flyway/FlywayModule.scala
  grpc-server/src/main/scala/com/avast/sst/grpc/server/GrpcServerModule.scala
  http4s-client-blaze/src/main/scala/com/avast/sst/http4s/client/Http4sBlazeClientModule.scala
  http4s-server-blaze/src/main/scala/com/avast/sst/http4s/server/Http4sBlazeServerModule.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/MicrometerHttp4sServerMetricsModule.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/RouteMetrics.scala
  http4s-server/src/main/scala/com/avast/sst/http4s/server/Http4sRouting.scala
  http4s-server/src/main/scala/com/avast/sst/http4s/server/middleware/CorrelationIdMiddleware.scala
  jvm/src/main/scala/com/avast/sst/jvm/execution/ExecutorModule.scala
  jvm/src/main/scala/com/avast/sst/jvm/system/console/Console.scala
  jvm/src/main/scala/com/avast/sst/jvm/system/console/ConsoleModule.scala
  jvm/src/main/scala/com/avast/sst/jvm/system/random/Random.scala
  jvm/src/main/scala/com/avast/sst/jvm/system/random/RandomModule.scala
  micrometer-jmx/src/main/scala/com/avast/sst/micrometer/jmx/MicrometerJmxModule.scala
  micrometer-jmx/src/main/scala/com/avast/sst/micrometer/jmx/TypeScopeNameObjectNameFactory.scala
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDModule.scala
  project/BuildSettings.scala
  project/Dependencies.scala
  project/plugins.sbt
  pureconfig/src/main/scala/com/avast/sst/pureconfig/PureConfigModule.scala
  ssl-config/src/main/scala/com/avast/sst/ssl/SslContextModule.scala
Labels: bug, build, dependency-update

#148 Update micrometer-core, ... to 1.3.5
  project/Dependencies.scala
Labels: dependency-update

#149 style: Reconfigure Scalafmt and reformat the whole project
  .scalafmt.conf
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/CassandraDatastaxDriverModule.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/CassandraDatastaxDriverConfig.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/advanced.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/basic.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/package.scala
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/config/profile.scala
  doobie-hikari/src/main/scala/com/avast/sst/doobie/DoobieHikariConfig.scala
  doobie-hikari/src/main/scala/com/avast/sst/doobie/DoobieHikariModule.scala
  example/src/main/scala/com/avast/sst/example/Main.scala
  example/src/main/scala/com/avast/sst/example/config/Configuration.scala
  example/src/main/scala/com/avast/sst/example/module/Http4sRoutingModule.scala
  flyway/src/main/scala/com/avast/sst/flyway/FlywayConfig.scala
  flyway/src/main/scala/com/avast/sst/flyway/FlywayModule.scala
  grpc-server/src/main/scala/com/avast/sst/grpc/server/GrpcServerConfig.scala
  grpc-server/src/main/scala/com/avast/sst/grpc/server/GrpcServerModule.scala
  http4s-client-blaze/src/main/scala/com/avast/sst/http4s/client/Http4sBlazeClientConfig.scala
  http4s-client-blaze/src/main/scala/com/avast/sst/http4s/client/Http4sBlazeClientModule.scala
  http4s-client-blaze/src/test/scala/com/avast/sst/http4s/client/Http4SBlazeClientTest.scala
  http4s-client-monix-catnap/src/main/scala/com/avast/sst/http4s/client/monix/catnap/Http4sClientCircuitBreakerModule.scala
  http4s-server-blaze/src/main/scala/com/avast/sst/http4s/server/Http4sBlazeServerConfig.scala
  http4s-server-blaze/src/main/scala/com/avast/sst/http4s/server/Http4sBlazeServerModule.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/RouteMetrics.scala
  http4s-server/src/main/scala/com/avast/sst/http4s/server/middleware/CorrelationIdMiddleware.scala
  http4s-server/src/test/scala/com/avast/sst/http4s/server/middleware/CorrelationIdMiddlewareTest.scala
  jvm/src/main/scala/com/avast/sst/jvm/execution/ConfigurableThreadFactory.scala
  jvm/src/main/scala/com/avast/sst/jvm/execution/ExecutorModule.scala
  jvm/src/main/scala/com/avast/sst/jvm/execution/ForkJoinPoolConfig.scala
  jvm/src/main/scala/com/avast/sst/jvm/execution/ThreadPoolExecutorConfig.scala
  micrometer-jmx/src/main/scala/com/avast/sst/micrometer/jmx/MicrometerJmxConfig.scala
  micrometer-jmx/src/main/scala/com/avast/sst/micrometer/jmx/MicrometerJmxModule.scala
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDConfig.scala
  micrometer-statsd/src/main/scala/com/avast/sst/micrometer/statsd/MicrometerStatsDModule.scala
  monix-catnap/src/main/scala/com/avast/sst/monix/catnap/CircuitBreakerConfig.scala
  monix-catnap/src/main/scala/com/avast/sst/monix/catnap/CircuitBreakerModule.scala
  ssl-config/src/main/scala/com/avast/sst/ssl/SslContextModule.scala
Labels: build

#150 Update flyway-core to 6.2.3
  project/Dependencies.scala
Labels: dependency-update

#151 Update grpc-netty-shaded, grpc-protobuf, ... to 1.27.1
  project/Dependencies.scala
Labels: dependency-update

#152 Update http4s-blaze-client, ... to 0.21.1
  project/Dependencies.scala
Labels: dependency-update

#155 Update scalafmt-core to 2.4.1
  .scalafmt.conf
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/CassandraDatastaxDriverModule.scala
  http4s-client-blaze-pureconfig/src/main/scala/com/avast/sst/http4s/client/pureconfig/ConfigReaders.scala
  http4s-server-micrometer/src/main/scala/com/avast/sst/http4s/server/micrometer/RouteMetrics.scala
Labels: dependency-update

#156 Update silencer-lib, silencer-plugin to 1.5.0
  project/Dependencies.scala
Labels: dependency-update

#157 Update flyway-core to 6.2.4
  project/Dependencies.scala
Labels: dependency-update

#158 Update scalatest to 3.1.1
  project/Dependencies.scala
Labels: dependency-update

#159 Update sbt-microsites to 1.1.2
  project/plugins.sbt
Labels: dependency-update

#160 Update silencer-lib, silencer-plugin to 1.6.0
  project/Dependencies.scala
Labels: dependency-update

#161 Update ssl-config-core to 0.4.2
  project/Dependencies.scala
Labels: dependency-update

#162 Update scalafmt-core to 2.4.2
  .scalafmt.conf
Labels: dependency-update

#163 Update sbt-tpolecat to 0.1.11
  project/plugins.sbt
Labels: dependency-update

#164 Update java-driver-core to 4.5.0
  project/Dependencies.scala
Labels: dependency-update

#165 Update grpc-netty-shaded, grpc-protobuf, ... to 1.27.2
  project/Dependencies.scala
Labels: dependency-update

#166 Update pureconfig to 0.12.3
  project/Dependencies.scala
Labels: dependency-update
