Repository avast/scala-server-toolkit, pull requests merged in 2020-03, with the labels that each got.

#167 Update cats-effect to 2.1.2
  project/Dependencies.scala
Labels: dependency-update

#170 Update zio-interop-cats to 2.0.0.0-RC11
  project/Dependencies.scala
Labels: dependency-update

#171 Update flyway-core to 6.3.0
  project/Dependencies.scala
Labels: dependency-update

#169 Update zio to 1.0.0-RC18-1
  .github/workflows/build.yml
  .github/workflows/pull.yml
  .github/workflows/release.yml
  project/Dependencies.scala
Labels: dependency-update

#172 Update sbt-scalafmt to 2.3.2
  project/plugins.sbt
Labels: dependency-update

#173 Update sbt-microsites to 1.1.3
  project/plugins.sbt
Labels: dependency-update

#174 Update grpc-netty-shaded, grpc-protobuf, ... to 1.28.0
  project/Dependencies.scala
Labels: dependency-update

#175 Update postgresql to 42.2.11
  project/Dependencies.scala
Labels: dependency-update

#176 Update zio to 1.0.0-RC18-2
  project/Dependencies.scala
Labels: dependency-update

#177 Update zio-interop-cats to 2.0.0.0-RC12
  project/Dependencies.scala
Labels: dependency-update

#178 Update flyway-core to 6.3.1
  project/Dependencies.scala
Labels: dependency-update

#179 Update micrometer-core, ... to 1.3.6
  project/Dependencies.scala
Labels: dependency-update

#182 Update/sbt scalafix 0.9.12
  cassandra-datastax-driver/src/main/scala/com/avast/sst/datastax/DatastaxHelper.scala
  project/BuildSettings.scala
  project/Dependencies.scala
  project/plugins.sbt
Labels: dependency-update

#183 feat: Add makeMaybe method to SslContextModule
  ssl-config/src/main/scala/com/avast/sst/ssl/SslContextModule.scala
Labels: feature

#184 Update sbt-microsites to 1.1.4
  project/plugins.sbt
Labels: dependency-update

#185 Update sbt-microsites to 1.1.5
  project/plugins.sbt
Labels: dependency-update

#186 Update micrometer-core, ... to 1.4.0
  project/Dependencies.scala
Labels: dependency-update

#187 fix: Add micrometer-statsd-pureconfig to root project aggregate
  build.sbt
Labels: bug

#188 Update flyway-core to 6.3.2
  project/Dependencies.scala
Labels: dependency-update

#189 Update http4s-blaze-client, ... to 0.21.2
  project/Dependencies.scala
Labels: dependency-update

#190 feat: Implement gRPC server logging and monitoring interceptors
  build.sbt
  grpc-server-micrometer/src/main/scala/com/avast/sst/grpc/server/micrometer/MonitoringServerInterceptor.scala
  grpc-server/src/main/scala/com/avast/sst/grpc/server/interceptor/LoggingServerInterceptor.scala
Labels: feature

#191 Update sbt-missinglink to 0.3.0
  project/plugins.sbt
Labels: dependency-update

#192 feat: Implement SentryModule and PureConfig integration
  build.sbt
  http4s-server-blaze/src/main/scala/com/avast/sst/http4s/server/Http4sBlazeServerModule.scala
  project/Dependencies.scala
  sentry-pureconfig/src/main/scala/com/avast/sst/sentry/pureconfig/ConfigReaders.scala
  sentry-pureconfig/src/main/scala/com/avast/sst/sentry/pureconfig/implicits.scala
  sentry/src/main/scala/com/avast/sst/sentry/SentryConfig.scala
  sentry/src/main/scala/com/avast/sst/sentry/SentryModule.scala
  site/docs/subprojects/sentry.md
  site/menu.yml
Labels: feature

#193 fix: Adjust the Sentry release property format according to the docs
  sentry/src/main/scala/com/avast/sst/sentry/SentryModule.scala
Labels: bug

#194 Update micrometer-core, ... to 1.4.1
  project/Dependencies.scala
Labels: dependency-update

#195 Update sbt-scalafix to 0.9.13
  project/plugins.sbt
Labels: dependency-update

#196 Update sbt to 1.3.9
  project/build.properties
Labels: dependency-update
